env:
  browser: true
  es6: true
  amd: true
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console:
    - off
  strict:
    - error
  prefer-const:
    - error
  no-var:
    - error
  eqeqeq:
    - error
plugins:
  - requirejs
